spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/files?createDatabaseIfNotExist=true
    username: lazarev
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size (max size of one file)
      max-file-size: 5MB
      # Max Request Size (all files together)
      max-request-size: 7MB