version: '3.9'

services:
  master-db:
    image: postgres
    container_name: master-db-logic
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - ./postgresql/master-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: master_db
      PGDATA: /var/lib/postgresql/data/master
  replica-db:
    image: postgres
    container_name: replica-db-logic
    ports:
      - "5434:5434"
    command: -p 5434
    volumes:
      - ./postgresql/replica-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: replica_db
      PGDATA: /var/lib/postgresql/data/replica

#su - postgres -c "pg_basebackup --host=master-db --port 5433 --username=repluser --pgdata=/var/lib/postgresql/data/replica"