management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: '*'

info:
  application:
    name: 'spring-actuator'
    description: 'spring boot actuator demo app'
    version: '1.0'