server:
  port: 8090

spring:
  security:
    oauth2:
      client:
        registration:
          my-client:
            client-name: my-client
            provider: spring
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8090/login/oauth2/code/client
            scope: openid
        provider:
          spring:
            issuer-uri: 'http://localhost:9000'

