create table roles(
    id   int4 generated by default as identity,
    name varchar(255),
    primary key (id)
);

create table users(
    id       int4 generated by default as identity,
    email    varchar(255),
    login    varchar(255),
    password varchar(255),
    primary key (id),
    constraint login_unique_idx unique (login),
    constraint email_unique_idx unique (email)
);

create table users_roles(
    user_id int4 not null,
    role_id int4 not null,
    primary key (user_id, role_id),
    constraint role_fk_constraint
        foreign key (role_id) references roles,
    constraint user_fk_constraint
        foreign key (user_id) references users
);